### ISSUE TITLE
Problem with importing data in .eeg format (BrainVision format)

### ISSUE THREAD

**Issue by andrazm** [sccn/bids-matlab-tools#1]
Hello,
I tried to use function pop_importbids with example datasets mentioned in the paper about EEG-BIDS (https://doi.org/10.1038/s41597-019-0104-8). In particular, I had an issue with importing data from The Matching Pennies dataset and rs-EEG-fMRI dataset which both contain EEG data in BrainVision format. The error was the following:

```
Unable to perform assignment with 0 elements on the right-hand side.

Error in pop_importbids (line 157)
            eegFileRaw  = allFiles{ind};
```

I believe there is a mistake in the code, so I changed lines
```
ind = strmatch( '.eeg', allFiles);
if ~isempty(ind)
    error(sprintf('No EEG data found for subject %s', bids.participants{iSubject,1}));
end
eegFileRaw  = allFiles{ind};
```
with

```
ind = strmatch( '.vhdr', cellfun(@(x)x(end-4:end), allFiles, 'uniformoutput', false) );
if isempty(ind)
    error(sprintf('No EEG data found for subject %s', bids.participants{iSubject,1}));
end
eegFileRaw  = allFiles{ind};
```

Additionally, after I fixed this i got an error at the line 179, so I changed lines 179-180 to

```
case '.vhdr',
    EEG = pop_loadbv( subjectFolder{iFold}, [tmpFileName '.vhdr'] );
```

After that it worked without a problem. I'm attaching the corrected file (extension should be changed to *.m).

[pop_importbids.txt](https://github.com/sccn/bids-matlab-tools/files/3359069/pop_importbids.txt)

**Comment by CPernet** [comment]
@arnodelorme this should be merged

**Comment by arnodelorme** [comment]
Merged.
