### ISSUE TITLE
BIDS Export Error

### ISSUE THREAD

**Issue by ams023** [sccn/bids-matlab-tools#10]
When exporting data for Emotions project to /data/projects/BIDSfiles/AS-ImaginedEmotionCont/BIDS, the following error popped up "EEGlab error in function pop_exportbids() at line 146: unable to perform assignment because the indices on the left side are not compatible with the size of the right side."
![Export Error2](https://user-images.githubusercontent.com/65685539/82716339-d350f580-9c4b-11ea-842e-6af240000164.JPG)

**Comment by dungscout96** [comment]
Fixed in 95e05bad7d61c15b5b4713eb0d4343b5c6ec1c0e
