### ISSUE TITLE
fieldnames error and bids_export error with the same data set

### ISSUE THREAD

**Issue by asalazar4** [sccn/bids-matlab-tools#103]
While working with a dataset (/data/qumulo/Annalisa/Inprogress/MAVIS_OSF/MAVIS) using the BIDS GUI, I encountered the following errors. 
- When opening the 'edit BIDs event info' tab, I received this fieldnames error message: Invalid input argument of type ‘double’. Input must be a structure or a Java or COM object., This is not a bug (Error occurred in function pop_eventinfo/newEventBIDS() at line 556)
- When attempting to export, I received this error: bids_export error: argument 'pInfoDesc' must be a structure, This is not a bug (Error occurred in function bids_export () at line 274)

![MAVIS_OSF-fieldnames_error](https://user-images.githubusercontent.com/93274767/144920376-3dffc881-414d-40f4-a212-74cd36505d2b.PNG)
![MAVIS_OSF-bids_export_error](https://user-images.githubusercontent.com/93274767/144920373-613c1cf9-e60f-45fb-89ae-9505aa28306f.PNG)

**Comment by dungscout96** [comment]
This should be fixed now
