### ISSUE TITLE
Scan fields in event TSV files

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#104]
In line 70 of pop_importbids we have

```
type_fields = { 'value' 'trial_type' };
```

Change this line to read event fields from TSV files (exclude "sample", "onset", "response_time", "duration").
So for example, if in the events.tsv file, we have columns onset, sample, c1, c2, trial_type, c3, duration, response_time, the list would be { 'c1' 'c2' 'trial_type', 'c3' })

You could look at the function bids_gettaskfromfolder() which also scans the directory structure to find files.

**Comment by dungscout96** [comment]
implemented in [a3cde2a](https://github.com/sccn/bids-matlab-tools/commit/a3cde2a5c976b04b8027e6cd5a235b9b842bcbd1)
