### ISSUE TITLE
bids_export: update default `createids` behavior

### ISSUE THREAD

**Issue by chriscline** [sccn/bids-matlab-tools#106]
The `bids_export` help documentation indicates that `createids` defaults to `'off'`. However, it actually defaults to `'on'`. Should update one or the other to be consistent.

https://github.com/sccn/bids-matlab-tools/blob/c64ed18628f671b6ad2ca91bb290ebe4b9a849f3/bids_export.m#L181
https://github.com/sccn/bids-matlab-tools/blob/c64ed18628f671b6ad2ca91bb290ebe4b9a849f3/bids_export.m#L268

**Comment by dungscout96** [comment]
Thanks for detecting it. Fixed in [93567d1](https://github.com/sccn/bids-matlab-tools/commit/93567d1cfd97e4f02deb817591e1870777a6cf87)
