### ISSUE TITLE
BIDS Export Error 5/27/20

### ISSUE THREAD

**Issue by ams023** [sccn/bids-matlab-tools#11]
When exporting error for line 938 is given: Invalid field name(s) TaskName for structure gInfo.
![BISD Export-TwoBack-Error](https://user-images.githubusercontent.com/65685539/83187462-0cbdb100-a0e3-11ea-8fbe-f2b04aff3ccb.JPG)

**Comment by ams023** [comment]
Issue was also seen on 5/28/20, reading "Invalid field name(s) README TaskName for structure ginfo.
![BIDS Export Error-README](https://user-images.githubusercontent.com/65685539/83187936-cb79d100-a0e3-11ea-8e87-638aca27ceb4.JPG)

**Comment by dungscout96** [comment]
Fixed in 971dc7176b06413d45c1b7d7d9bf004340d256df
