### ISSUE TITLE
There is no file in the EEG struct: https://github.com/sccn/bids-matlab-tools/blob/master/bids_export.m#L329

### ISSUE THREAD

**Issue by ChengtengIp** [sccn/bids-matlab-tools#115]
Hi, 
In this line, it checks if there is a variable 'file'. But in the EEG struct created by eeglab, it has only filename. Maybe it is a possible bug?
Best regards,
Cheng-Teng

**Comment by dungscout96** [comment]
Here `file` is a field of `files`, not of `EEG` struct. Did you receive an error related to this?

**Comment by dungscout96** [comment]
Close due to no follow up
