### ISSUE TITLE
[Improvement] https://github.com/sccn/bids-matlab-tools/blob/master/bids_export.m#L663

### ISSUE THREAD

**Issue by ChengtengIp** [sccn/bids-matlab-tools#116]
Hi,
I have a study with multiple sessions, tasks, and runs for each subject. But for one subject has a missing file on the first run and only has the second run. BIDs-matlab will give me an error and stop running further. I have it should make a warning instead and proceed further. Especially when a subject has a bad first run due to any technical reason. 
Best regards,
Cheng-Teng

**Comment by dungscout96** [comment]
Can you provide more details? What error did it give out exactly on which line of the function?

**Comment by dungscout96** [comment]
Close due to no follow up
