### ISSUE TITLE
Participant Info-HeadCircumference

### ISSUE THREAD

**Issue by ams023** [sccn/bids-matlab-tools#12]
Saved information for head circumference in participant info was changed to 'NaN' instead of the measurements or NA if information was not available.
![HeadCircumference NaN](https://user-images.githubusercontent.com/65685539/83188184-27445a00-a0e4-11ea-92e8-fbbb9178de5c.JPG)

**Comment by dungscout96** [comment]
Fixed in fdf66bfc75c7cd2f74328b9dbba6d53a7761f343
