### ISSUE TITLE
export issues -- sessions or run STUDY number

### ISSUE THREAD

**Issue by CPernet** [sccn/bids-matlab-tools#121]
We export using the order as numeric for sessions, runs, etc ... but one should use string as people may have things such as _session1 run 1 session 1 run 3 session run 2 session 2 run 3_ ... we must be able to handle this without screwing the order (name string) specified and not rely on internal indexing

**Comment by arnodelorme** [comment]
Good point. Does BIDS allow for arbitrary session and run strings, e.g. sessionxyz_runkij?

**Comment by Remi-Gau** [comment]
Most entities use a label format (see for example here in the BIDS schema for session)

https://github.com/bids-standard/bids-specification/blob/9842cea7cab7b0493a7d7ef496401692d587216d/src/schema/objects/entities.yaml#L288

The label format is specified as `[0-9a-zA-Z]+` here:

https://github.com/bids-standard/bids-specification/blob/9842cea7cab7b0493a7d7ef496401692d587216d/src/schema/objects/formats.yaml#L14

**Comment by CPernet** [comment]
It does - values of keys sub- ses- run- task- are any string (well any we can recode hence the new function on eeglab misc that cleans your string)Sent from my Huawei phone-------- Original message --------From: Arnaud Delorme ***@***.***>Date: Thu, 5 May 2022, 08.46To: sccn/bids-matlab-tools ***@***.***>Cc: Cyril Pernet ***@***.***>, Author ***@***.***>Subject: Re: [sccn/bids-matlab-tools] export issues -- sessions or run STUDY number (Issue #121)
Good point. Does BIDS allow for arbitrary session and run strings, e.g. sessionxyz_runkij?

**Comment by arnodelorme** [comment]
Is that what you wanted? See branch the very descriptive branch "pernet_x"

![Screen Shot 2022-05-09 at 6 57 55 PM](https://user-images.githubusercontent.com/1872705/167527637-545e2f73-61a7-45a4-a1a1-16a30481eaf0.png)
![Screen Shot 2022-05-09 at 6 57 44 PM](https://user-images.githubusercontent.com/1872705/167527640-5471d1ac-0de8-4c3b-a3a8-622dc424d95a.png)

**Comment by arnodelorme** [comment]
And run bids_export_example4 to test

**Comment by arnodelorme** [comment]
Closing this for now and merging the branch with master.
