### ISSUE TITLE
Task Description was not presented in the eeg.json from the export function in bids-matlab-tool 

### ISSUE THREAD

**Issue by ChengtengIp** [sccn/bids-matlab-tools#123]
Hi, in the bids-matlab-tool, there is a place where I can key in the task description but however I could not find the information save anywhere in the eeg.json files.

**Comment by arnodelorme** [comment]
The task description is saved in the _eeg.json files. There are also information saved in the README.txt file and in the instruction field. https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#sidecar-json-_eegjson
