### ISSUE TITLE
Unable to upload participant descriptions on PC

### ISSUE THREAD

**Issue by couperuj** [sccn/bids-matlab-tools#125]
I am trying to export large EEG datasets (ie approx. 300 participants) and would like to include some basic demographics (age, gender, etc.). However, when I try to upload my excel data while it recognizes the columns when I then go to import them it gives me the error "no matched subject between dataset and spreadsheet found." Given I directly typed each individual participant number into the EEG study from the excel sheet I am using I know they are all direct matches. I also can't appear to copy and past columns into the gui so I would have to manually enter each participants information (not going to happen!). Any ideas why this may not be working?

**Comment by arnodelorme** [comment]
Did you watch this video https://www.youtube.com/watch?v=qxKMH4pSvx8
It does exactly what you want to do.
Send us a zip folder with just one or two subjects demonstrating the problem if you cannot solve your problem.

**Comment by couperuj** [comment]
Hi,
 The attached video is not using the GUI interface in EEGLab but is instead
a code version. The issue I am having is with the GUI interface when trying
to convert EEG data which has been uploaded into a Study on EEGLab through
the GUI. The GUI is not uploading the excel (or .txt or other versions) and
recognizing the match between subject numbers in the study and subject
numbers in the sheet. I have also tried using full file names versus the
numbers used when creating the study in EEGLab. Neither has worked. If I
have to do this all through coding I will, but I was hoping to use the GUI
as I'm not an expert coder.
Best, Jane

**Comment by couperuj** [comment]
Hi again,
 Realized I could/should upload files for an example. Attached is a small
version of the study along with the excel sheet of participant info
 testdata.zip
<https://drive.google.com/file/d/11AEXbLwVmZCYmmpu-2vQWqNuuj95Hfi2/view?usp=drive_web>

**Comment by arnodelorme** [comment]
OK, will look into it.

**Comment by arnodelorme** [comment]
Good. Thanks
