### ISSUE TITLE
BIDS Export Error

### ISSUE THREAD

**Issue by ams023** [sccn/bids-matlab-tools#13]
Error message upon export: "No session info found in either EEG or STUDY .datasetinfo. Please add using study>editSTUDY info line 130. The data set is fully loaded.
![BIDS Error line 130](https://user-images.githubusercontent.com/65685539/83311347-cbe99900-a1c3-11ea-9d91-8464d4b01ac9.JPG)

**Comment by dungscout96** [comment]
Have you checked to see if session info is entered for the Study?

**Comment by ams023** [comment]
That was the issue. Export was successful.
