### ISSUE TITLE
BIDS Import Error

### ISSUE THREAD

**Issue by pakingan** [sccn/bids-matlab-tools#137]
https://drive.google.com/drive/folders/1YlzF9AG1hxU8bowuHuevSTSzdn6cLF4g

Tried to import the BIDS_EXPORT_2 folder and got this error

**Comment by pakingan** [comment]
![BIDS export error](https://user-images.githubusercontent.com/109559676/182254411-33c595b0-6ae8-42a3-8e8b-84b043e6a05c.PNG)

**Comment by arnodelorme** [comment]
@dungscout96 can we write a test script using these 2 files for export/reimport and checking that it is all the same?

**Comment by arnodelorme** [comment]
The files are a little large to add to this repo, but maybe make them each 1 Mb, so way we have a folder "test" in this report for testing purposes.

**Comment by dungscout96** [comment]
fixed in 750a8fee99d188ec339fd3b6227d9cddf891b22b. We can create test case but there's current bug in bids_export. Will submit a separate issue.
