### ISSUE TITLE
pop_bidsimport default options

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#138]
If there is no channel file, there is a crash. Is the channel file required?

If there is no event file, there is a crash. The 'bidsevents' option is on by default, but if there is no event, it should not cause the function to crash by default. Pull changes, then to test

```
eeglabp = fileparts(which('eeglab'));
[TMP,TMP2] = pop_importbids( fullfile(eeglabp, 'sample_data', 'test_data', 'BIDS_test') );
```

**Comment by dungscout96** [comment]
channels.tsv is not required but events.tsv is. We can change bidschanloc to off by default. The plugin imports fine with bidsevents off and there's no events.tsv if users want to do it that way.

**Comment by arnodelorme** [comment]
I think we want to have bidsevents on by default but not crash when there are no events.

**Comment by dungscout96** [comment]
This is now handled
