### ISSUE TITLE
Repository too large

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#140]
The test files are too large (100Mb). Replace with smaller ones so people do not have to download that much data to install the plugin.

**Comment by dungscout96** [comment]
I tracked the testing directory with LFS so now if users download the repo it's only ~500KB. Now I learned the hard way that later version of `git clone` actually pulls LFS files by default (during checkout). So if they have git lfs installed the files will still be downloaded, but that's probably not the common case.
