### ISSUE TITLE
BIDS task name is not being used

### ISSUE THREAD

**Issue by dungscout96** [sccn/bids-matlab-tools#142]
Currently we're relying on `EEG.task`: https://github.com/sccn/bids-matlab-tools/blob/d92f9acf7a2c2d0fb08c3b3738b602343872fe7f/pop_exportbids.m#L167

which propagate to export_bids as well. e.g.
https://github.com/sccn/bids-matlab-tools/blob/d92f9acf7a2c2d0fb08c3b3738b602343872fe7f/bids_export.m#L345

Can change the behavior to replace EEG.task to task name from BIDS if exists for pop_exportbids?

**Comment by arnodelorme** [comment]
The problem is that there can be multiple task names which is why we did that. Let's discuss.
