### ISSUE TITLE
default readme in BIDS dataset after conversion

### ISSUE THREAD

**Issue by Remi-Gau** [sccn/bids-matlab-tools#143]
hey

We (BIDS maintainers) are trying to see if we can improve the quality of the average README in BIDS dataset. Those tend to be pretty thin and are missing some information we would like to see there even if it cannot be formalized "yet" into the BIDS specification.

Hoping to leverage the bids converters to help to do.

So I am going around the different BIDS converters repo to see if we can start improving the  default README they put in a the BIDS dataset.

There is template that is provided in the BIDS starter kit: https://github.com/bids-standard/bids-starter-kit/blob/main/templates/README.MD

Some possible options:
1. use this template is
2. use a subset of it
3. add a link to the template README
4. something else (a mix of 2 and 3?)

What do you think? I can try to open a PR if you want.

Also let us know if you think that the template README in the starter kit could / should be improved .

Feel free to disregard if you are already using some version of the template README.

**Comment by arnodelorme** [comment]
This is a worthwhile endeavor. I think this should be formalized in a sidecar file to be useful although as a first step a README file might be useful.
Attaching the Fields OpenNeuro uses on their website. It would greatly increase adoption if you use the same. Also OpenNeuro could automatically generate sidecar files since they have that Information in their database.

**Comment by arnodelorme** [comment]
![Screen Shot 2022-08-08 at 9 46 55 AM](https://user-images.githubusercontent.com/1872705/183470694-f43a4184-bfcb-45b7-a34b-6b4a909dddbe.png)
![Screen Shot 2022-08-08 at 9 46 49 AM](https://user-images.githubusercontent.com/1872705/183470704-cb80d03c-5c4e-460f-9984-7e83f6ab3336.png)
![Screen Shot 2022-08-08 at 9 46 42 AM](https://user-images.githubusercontent.com/1872705/183470707-20904076-284e-4b43-96d6-db64540c3340.png)
![Screen Shot 2022-08-08 at 9 46 20 AM](https://user-images.githubusercontent.com/1872705/183470709-0ac0cb9e-bd18-4e73-8932-41ab7f0af725.png)

**Comment by arnodelorme** [comment]
CCing @robertoostenveld and @sappelhoff (please move the discussion to relevant BIDS channels, although it probably has already occurred there?).

**Comment by robertoostenveld** [comment]
For reference, https://github.com/fieldtrip/fieldtrip/pull/2286 is how I propose to do it with FieldTrip. It allows the user to specify a multi-line string in their script, and it uses the template README from the starter kit as default.
