### ISSUE TITLE
Importing motion-bids data through bids-matlab tools 

### ISSUE THREAD

**Issue by sjeung** [sccn/bids-matlab-tools#146]
Hello Arno, 

I hope you are doing well, as discussed some time ago, I would like to hear out what you think of importing Motion data together with EEG. 

Here is the [MoBI-version](https://github.com/BeMoBIL/bemobil-pipeline/blob/master/pop/pop_importbids_mobi.m) of your script that I have modified to also import motion data in BIDS format into eeglab. For us to synchronize EEG and motion data for further processing it is very convenient to import it together with EEG and have it saved as .set format. 

The question is, whether you deem it proper to reflect this change to official bids-matlab-tools script. If that is the case, I will refactor this and submit a proper pull request. 
Otherwise, it is also an option to keep the diverged copy of the script within the BeMoBIL pipeline. 

Please let me know what you prefer, thanks! 

Best, 
Sein

**Comment by dungscout96** [comment]
bids-motion import is now supported
