### ISSUE TITLE
Error in function eeg_importeventsfiles() at line 69: undefined function 'cleanvarname' for input arguments of type 'char'.

### ISSUE THREAD

**Issue by empetrucci** [sccn/bids-matlab-tools#148]
Hello and thank you for taking the time to help me out!

I modified your bids_export_example.m to suit my dataset and created a BIDS formatted directory (script included in zip file as bids_export_NFA.m). I have not yet added all of the detailed information about file quality, task/participant information, authors, etc., but when I use the "validate BIDS dataset" tool, I do not seem to get any errors besides having too few authors listed.

Unfortunately, when I try to import the BIDS dataset into EEGLab (File > Import data > using EEG functions and plugins > From BIDS folder structure), I get an error that the function 'cleanvarname' is undefined, as stated in the title. I cannot find this function in any of the EEGLab folders, nor can I find this function in the MATLAB directory - where is this function supposed to be defined? When I use the testing script (unittests.m) and sample data included under the testing folder, I get the same error.

I could not get the zip file to be small enough to upload here, so here is a [Google Drive link.](https://drive.google.com/file/d/10KR79qc0S3ia9S2ctyZJnmjLJNolWWm7/view?usp=sharing)

Would appreciate any insight you could give to resolve this problem!
Gratefully,
Emily Petrucci

**Comment by cmmrandau** [comment]
I second this issue. Receiving the same on bids-matlab-tools 7. Removing cleanvarnames makes it run and it seems to work:
```
    for iField = 1:length(eventData(1,:))
        eventData{1,iField} = eventData{1,iField}; % cleanvarname(eventData{1,iField});
    end
```

**Comment by empetrucci** [comment]
Yeah the function file was/is missing, as soon as they sent me the file and
I put it in the proper location (functions/miscfunc), everything worked as
it should for me as well!

**Comment by jnvandermeer** [comment]
For more info, the function cleanvarname you can find in the eeglab Github repository.

Just search that and you can copy/paste the function into your own eeglab installation. Or maybe re-download eeglab again (but that is a bit of a hassle).

I guess that it is a recent-ish addition to EEGlab! It may be good not to depend on it (yet), or alternatively to unabiguously state that LIMO (preprocessing tutorial) only works with the most recent version of eeglab?

**Comment by dungscout96** [comment]
`cleanvarname` is now part of EEGLAB core functions. Closing this issue but please let us know if you still find the problem
