### ISSUE TITLE
bids_export.m fix for recording duration (line 867)

### ISSUE THREAD

**Issue by drpedapati** [sccn/bids-matlab-tools#151]
Great code Arno- working on a front end wrapper for multisite trials.

On line 867
tInfo.RecordingDuration = EEG.pnts/EEG.srate;

which is identical to  tInfo.EpochLength = EEG.pnts/EEG.srate;

I think it should be something like:
tInfo.RecordingDuration = (EEG.pnts/EEG.srate)*EEG.trials;

Doesn't require a separate issue, but for taskname validation (short, no spaces, or specials) wrapping it in:
matlab.lang.makeValidName() may help.

**Comment by arnodelorme** [comment]
Multiple trial is good but is there a definition somewhere?

Yes, that sounds right
tInfo.RecordingDuration = (EEG.pnts/EEG.srate)*EEG.trials;
