### ISSUE TITLE
Where can I get the function, "bids_getinfofromfolder"?

### ISSUE THREAD

**Issue by jeongwoochoi83** [sccn/bids-matlab-tools#154]
It seems like in the latest "pop_importbids.m" function, a newer inherent function, "bids_getinfofromfolder", is used to get all relevant information from the folder names such as tasks, sessions, runs. However, I couldn't find this bids_getinfofromfolder function anywhere in the "bids-matlab-tools". Am I missing something or this function will be uploaded soon? 

Best,
Jeong Woo

**Comment by arnodelorme** [comment]
Added the function.
