### ISSUE TITLE
The unit should be uV, not microV

### ISSUE THREAD

**Issue by robertoostenveld** [sccn/bids-matlab-tools#155]
This applies to line https://github.com/sccn/bids-matlab-tools/blob/beba7fe3ed1da99fe24b6e04680ffe747a8a387e/eeg_writechanfile.m#L41

See https://bids-specification.readthedocs.io/en/stable/appendices/units.html

**Comment by arnodelorme** [comment]
Fixed in [922379a](https://github.com/sccn/bids-matlab-tools/commit/922379a40dd6b29465df2374fabc4eb2178b9a1d)
