### ISSUE TITLE
Rename face datasets NEMAR

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#158]
ds000117
ds003645 hed
ds002718 eeglab

Rename datasets
ds003645 -> Multisubject, multimodal face processing MEEG with HED tags
ds002718 -> Multisubject, multimodal face processing EEG for EEGLAB tutorial

**Comment by arnodelorme** [comment]
Think of a derived BIDS

**Comment by dungscout96** [comment]
The names have been changed accordingly
