### ISSUE TITLE
Can't load electrodes.tsv

### ISSUE THREAD

**Issue by crisglav** [sccn/bids-matlab-tools#164]
I have EEG data in bids format with two tasks in the shape:

```
sub-CONTRhc01_task-closed_eeg.eeg
sub-CONTRhc01_task-open_eeg.eeg
```

and one electrode file for both tasks named

`sub-CONTRhc01_electrodes.tsv
`
which is in accordance to the [bids specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#electrodes-description-_electrodestsv). That is, I don't need two electrode files named
```
 sub-CONTRhc01_task-closed_electrodes.tsv
 sub-CONTRhc01_task-closed_electrodes.tsv
```
However the code looks for these two files in the lines below, and therefore does not recognize my initial electrodes.tsv file.
https://github.com/sccn/bids-matlab-tools/blob/01d140cd7534348304c513d3e1a5ddaee9d86b44/pop_importbids.m#L319
https://github.com/sccn/bids-matlab-tools/blob/01d140cd7534348304c513d3e1a5ddaee9d86b44/pop_importbids.m#L331

Could you fix this issue? Thanks!

**Comment by arnodelorme** [comment]
Would you mind making your BIDS dataset available to us?

**Comment by crisglav** [comment]
Sure, here it is a subset with two participants:
https://syncandshare.lrz.de/getlink/fi4v5HsCh4QSZ1hVLWMrLx/bids_healthy.zip
I hope it works! Thanks for looking into it.

**Comment by dungscout96** [comment]
We have now performed a search for top-level files according to BIDS principle. Please pull the latest changes and let us know if the problem still persists for you.
