### ISSUE TITLE
BIDS update/download error

### ISSUE THREAD

**Issue by DiegoAndres7** [sccn/bids-matlab-tools#168]
After updating/downloading the BIDS Toolbox JSONio is empty, when attempting to run BIDS, it generates the specific error: "EEGLAB error in function bids_export() at line 333" "Undefined function 'jsonwrite' for input arguments of type 'struct'". This is easy to solve, copying the files from the BIDS repository to the JSONio. Then, adding properly the path of the JSONio folder in line 245: changing addpath(fullfile(fileparts(which(mfilename)), 'JSONio')); for addpath('path_for_JSONio/JSONio')), or simply adding the JSONio path once before to start eeglab.

**Comment by dungscout96** [comment]
This should no longer be an issue. Closing it now but please reopen if the issue still persists.
