### ISSUE TITLE
Event Info Error

### ISSUE THREAD

**Issue by ams023** [sccn/bids-matlab-tools#17]
When trying to review event info, I was given this error in Matlab and a blank screen in event info in BIDS.
![Event Info Error](https://user-images.githubusercontent.com/65685539/86277120-06f83700-bb8b-11ea-8523-a09a0698f918.JPG)
![Event Info Error 2](https://user-images.githubusercontent.com/65685539/86277132-0d86ae80-bb8b-11ea-85a9-21f223f6660d.JPG)

**Comment by arnodelorme** [comment]
This is usually due to conflict with other toolboxes such as Mobilab, SIFT or BCILAB. Can you type "which strjoin" on the Matlab command line?

**Comment by ams023** [comment]
Here is what I got

/data/common/matlab/eeglab/plugins/measure_projection/dependency/propertyGrid/strjoin.m

**Comment by arnodelorme** [comment]
Yes, this is the problem. I would remove the measure projection toolbox.

Arno

**Comment by ams023** [comment]
What would be the best way to remove it?
