### ISSUE TITLE
BIDS validation error2

### ISSUE THREAD

**Issue by RBguest** [sccn/bids-matlab-tools#171]
Downloaded 3 edf files, created study, exported study to the BIDS folder and BIDS_EXPORT folder was created after it. When I validated BIDS dataset the following MATLAB message appeared: "C:\Program' is not recognized as an internal or external command, operable program or batch file." Any ideas what should I do?

**Comment by RBguest** [comment]
The issue is solved after I reinstalled eeglab

**Comment by arnodelorme** [comment]
Thanks you for the update
