### ISSUE TITLE
Supporting export of other data formats

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#172]
Let’s see if we can accommodate the meta data for
- MEG
- iEEG
- Eye tracking (beta)
- Behavioral
- Motion capture

Our tool should be able to export all these type of data at the same time. The current format is

data(1).file to be renamed to data(1).eegfile

data(1).behfile currently data(1).beh

Then we would create 

data(1).megfile
data(1).eyefile
data(1).ieegfile
data(1).motionfile

I would propose to “copy_data_bids” and have one copy per format.
I can handle the eye tracking format with Deepa.

**Comment by dungscout96** [comment]
We have implementations for all of them now I believe
