### ISSUE TITLE
upload to OpenNeuro was successful, BUT...

### ISSUE THREAD

**Issue by RBguest** [sccn/bids-matlab-tools#180]
There was only one warning. I was able to see my files. However, Readme file was empty. It is not clear how can I upload different conditions from the same subject ( I have 4), because condition is not displayed in uploaded files. Any suggestions, how can I upload different conditions, because in OpenNeuro files were divided only on ses-1, ses-2 etc?

**Comment by dungscout96** [comment]
BIDS doesn't organize directories based on condition. You might want to reconsider specifying different tasks instead? Closing this for now but feel free to reopen with further information.
