### ISSUE TITLE
Extensions Writing Incorrectly (..set)

### ISSUE THREAD

**Issue by peclayson** [sccn/bids-matlab-tools#183]
I am running into an issue where the eeg file is getting written as (***..set & ***.fdt). 

I found in `bids_export.m` that it looks like lines 796-799 contain the culprit.
```
tInfo = opt.tInfo;
[~,~,ext] = fileparts(fileIn);
fileOut = [fileBase '_eeg.' ext];
fprintf('Processing file %s\n', fileOut);
```
`fileOut = [fileBase '_eeg.' ext];` should be `fileOut = [fileBase '_eeg' ext];`

`ext` already contains the `.` from `fileparts`. 

I'm using eeglab set files if that is relevant.

**Comment by arnodelorme** [comment]
Thank you. This was fixed in d8aec1b
