### ISSUE TITLE
motion capture issue (ds003846)

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#192]
Dataset ds003846 has motion data and cannot be imported. The issue is that the JSON file is not present.

https://nemar.org/dataexplorer/detail?dataset_id=ds003846

**Comment by arnodelorme** [comment]
<img width="1110" alt="Screen Shot 2023-11-28 at 2 10 13 PM" src="https://github.com/sccn/bids-matlab-tools/assets/1872705/baf4594b-c166-4470-abe4-03a8e4fe2d07">

**Comment by sjeung** [comment]
Probably both the data set and import tool need to be brought up-to-date with the current motion spec. 
I will submit the importer update before I go off on end of the year holiday.

**Comment by arnodelorme** [comment]
Thanks Sein

**Comment by arnodelorme** [comment]
Hi @sjeung happy new year! Any update? Tx

**Comment by sjeung** [comment]
> Hi @sjeung happy new year! Any update? Tx

Hello, happy new year to you, too! No matter which new year we follow I'm behind the schedule with this one. I will get to this now.

**Comment by arnodelorme** [comment]
Thanks, let us know when there is progress.

**Comment by sjeung** [comment]
Ok, this particular error seems to arise from nonadherence of the data set to the current motion spec. The .json accompanying motion.tsv should have a name matching the tsv file, 

'sub-1_ses-TestEMS_task-PredError_tracksys-HTCVive_motion.json'
for 
'sub-1_ses-TestEMS_task-PredError_tracksys-HTCVive_motion.tsv'

In the current data set, the metadata file is named 
'sub-1_ses-TestEMS_task-PredError_motion.json'. 

I will

1. also check if an up-to-date version can be imported using pop_importbids function, and submit needed changes to pop_importbids
2. and ping the owner of the repo to bring the data set up-to-date

**Comment by sjeung** [comment]
I tested bids matlab tools with a different data set and opened this pull request. #199 
Other than that it seems to work well

**Comment by lukasgehrke** [comment]
Hey @sjeung @arnodelorme, the dataset with accession number ds003846 has been updated on openneuro (https://openneuro.org/datasets/ds003846/versions/2.0.0). It should conform to the latest BIDS motion spec and pop_importbids works using @sjeung https://github.com/sjeung/bids-matlab-tools motion-bids branch as it needs to loop over multiple motion tracksys.

**Comment by arnodelorme** [comment]
OK, is it possible to issue a pull request on the main repo. The motion capture capabilities are beta, and so we can merge them in master. It is too complex for our research assistant to test a remote branch.

**Comment by sjeung** [comment]
Hi Arno, I believe PR #199 deals with this. Thanks for merging!

**Comment by arnodelorme** [comment]
Ah OK, thanks. @asalazar4 would you mind to try this dataset again?

**Comment by dungscout96** [comment]
Trying to import this dataset lead to a suggestion to the BIDS motion spec: https://github.com/bids-standard/bids-specification/pull/1817
We also detected an issue of `motion.json` not containing the required `SamplingFrequency` field, which we are currently ignoring for now. We have updated error message for this dataset on NEMAR however.
