### ISSUE TITLE
possible bug in case 3 % Mult-Session Single-Run

### ISSUE THREAD

**Issue by ugpavlov** [sccn/bids-matlab-tools#195]
line 789 bids_export.m

copy_data_bids_eeg( structOut, subjectStr, ['ses-' files(iSubj).session{iSet}], fileStr, opt);  

should probably be

copy_data_bids_eeg( structOut, subjectStr, ['ses-' files(iSubj).session{iSess}], fileStr, opt);

**Comment by dungscout96** [comment]
We have updated our export mechanism. This should be handled properly now
