### ISSUE TITLE
JSON sidecars

### ISSUE THREAD

**Issue by VisLab** [sccn/bids-matlab-tools#197]
It would be useful to have the information in the JSON sidecars, particularly the events.json stored in the etc field of EEG for reference.

Also, the tools may not be handling BIDS inheritance rules correctly.

**Comment by dungscout96** [comment]
Fixed inheritance principle implementation in #198 and 20b9047. All raw BIDS information are preserved in the structure EEG.BIDS. I have updated it to store `events.json` field as well with HED stored as string.
