### ISSUE TITLE
Dataset editing vs group editing

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#20]
<img width="1068" alt="Screen Shot 2020-08-20 at 1 59 16 PM" src="https://user-images.githubusercontent.com/1872705/90837436-bc26b000-e2ed-11ea-8cba-58f9fbd98cac.png">
@dungscout96 when editing a study and then going to edit a single dataset, the BIDS function return this warning. Pressing the YES button creates an error.

**Comment by dungscout96** [comment]
I tried loading a new study (EEGLAB example study), edit gender information for all subjects, clear study, load single dataset, edit gender info and received no error. I reloaded the study again after editing the single set and also didn't receive the reported error. The issue might have been fixed then.

Closing it for now and we can reopen if the issue reappear.

**Comment by arnodelorme** [comment]
Thanks Dung. Yes, I will continue testing. I have released a version
yesterday (which include some of your changes last week) because of other
changes I did.

Cheers,

Arno
