### ISSUE TITLE
bids_writetinfofile.m

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#203]
The file bids_writeieegtinfofile.m is organized in the same way as the definition

https://bids-specification.readthedocs.io/en/stable/modality-specific-files/intracranial-electroencephalography.html

- Do the same for bids_writetinfofile.
- Write the MEG information file bids_writemegtinfofile in a similar manner
- Check that MEG BIDS datasets generated in this way pass the BIDS validator

**Comment by dungscout96** [comment]
Implemented in #205

**Comment by arnodelorme** [comment]
Thanks for implementing that. Let’s get down the list of this plugin.
