### ISSUE TITLE
Fix default values

### ISSUE THREAD

**Issue by dungscout96** [sccn/bids-matlab-tools#21]
Current errors:

**eeg.json**
  "PowerLineFrequency": 0,
  "SoftwareFilters": "n/a",
  "EEGChannelCount": 0

**events.json**
  Missing default columns: sample, trial_type, response_time, stim_file

**Comment by dungscout96** [comment]
Fixed events.json in 4f97a8c.

For eeg.json fields, users should review their file to detect odd values and fill in the needed information using the tool.

**Comment by arnodelorme** [comment]
Hi Dung,

Are these questions for me?

Arno

**Comment by dungscout96** [comment]
They meant to be note-to-self but please comment if you have any thought!

**Comment by arnodelorme** [comment]
I would need more context.

For this one "Do we want Group info by default?”

I would say no.

Arno

**Comment by dungscout96** [comment]
Thanks Arno,
I was using the EEGLAB example study and when exporting to BIDS using default values there were some values that seem problematic.

For _eeg.json file, the EEGChannelCount and PowerLineFrequency are 0, and SoftwareFilters are "n/a".
![image](https://user-images.githubusercontent.com/10362238/91230698-d4793f00-e6e0-11ea-8fe5-e3bbf0cf90f9.png)

When I investigated the cause for EEGChannelCount to be 0, turned out that it's because in EEG.chanlocs the channel type is empty so all channels are counted as miscellaneous. And I learned that PowerLineFrequency and SoftwareFilters are REQUIRED by BIDS so I guess users must edit those info before exporting. 

events.tsv file has more default columns then were being described by events.json. I have fixed that.

participants.tsv has Gender, Age, and Group by default, while everything about participant info are RECOMMENDED by BIDS. Should I remove all three columns then? And not create participants.* files if there's no participant info inputted by defaults? We do try to extract participant info from EEG and STUDY structure when possible.

**Comment by arnodelorme** [comment]
Yes, we should fix the EEGChannelCount. If no channel of type EEG is found, assume they are all of type EEG. Will nan work for PowerLineFrequency and SoftwareFilters? For events, yes, you can remove the columns which are recommended but not required (if we do not have the information).
