### ISSUE TITLE
Events Error exporting to BIDS

### ISSUE THREAD

**Issue by nrosjat** [sccn/bids-matlab-tools#22]
When using the `bids_export_example.m` events are not correctly exported with our data files. 

- `onset`, `sample`, `response_time` and `stim_file` are all replaced by `n/a`
- `trial_type` is replaced by `Epoch` or `STATUS`

The event field values in EEGLAB display the correct values. Am I missing something?

**Comment by dungscout96** [comment]
Thanks @nrosjat for reporting. I have fixed the issue with default value for `onset`. Did you create an `eInfo` structure in the `bids_export_example.m` script? It would be helpful for us to see your `bids_export_example.m` and one example dataset containing your EEG.event for further investigation?

**Comment by arnodelorme** [comment]
Yes, please send us your data files. Here is another export script I am using in case that helps.

[bids_export_p300.m.zip](https://github.com/sccn/bids-matlab-tools/files/5388626/bids_export_p300.m.zip)

**Comment by nrosjat** [comment]
Sorry for the late response.

I was indeed missing the `eInfo` structure which was not mentioned in the `bids_export_example.m`. The example provided by @arnodelorme solved my problem.

**Comment by arnodelorme** [comment]
Wonderful.

Arno
