### ISSUE TITLE
Correct user feedback

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#26]
For the text on the command line

"Using tInfo of EEG(1)..."

Change to 

"Using task info of the first dataset for all datasets..."

When a study is selected, the feedback

"Using pInfoDesc of EEG(1)..."

Is not true, because it is using information from all datasets.

Arno

**Comment by dungscout96** [comment]
Since we're allowing editing participant info on single dataset level, we can't guarantee that pInfoDesc is consistent across all datasets of the STUDY, hence the current message. I'm changing the message to "Using pInfoDesc of the first dataset for all datasets...". What do you think?

**Comment by arnodelorme** [comment]
Let's use "Using BIDS information of the first dataset for all datasets..." People will not know what "pInfoDesc" means.

**Comment by dungscout96** [comment]
Thanks Arno. Fixed in aedd008
