### ISSUE TITLE
Event BIDS editor change

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#27]
Would it be possible to change this GUI and have in the first columns the BIDS fields and the second one the EEGLAB fields available to choose from. So in other word, we associate BIDS fields with EEGLAB fields and not the other way around.

**BIDS fields:**
onset
duration
sample
trial_type
response_time
stim_file
value
HED

**EEGLAB fields**
have the fields of the event structure with 2 entries for latency:
- latency (sample)
- latency (converted to s)

**Default association:**
onset -> latency (converted to s)
duration -> duration
sample -> latency (sample)
trial_type -> type
response_time
stim_file
value
HED -> hed

**Comment by arnodelorme** [comment]
I am convinced it makes more sense like this. This is also because you do not need to define levels for EEGLAB event fields (which are not associated with BIDS fields) - which is currently possible.

**Comment by arnodelorme** [comment]
We need to also have an option to add custom fields to BIDS. A button add/delete field.

**Comment by dungscout96** [comment]
Showing BIDS fields explicitly as first column makes a lot of sense, as we would want people to fill in as many BIDS fields as possible. 
Couple questions:
- For latency (sample) and latency (converted to s), does bids_export support these two options yet?
- This has been discussed many times (and I think BIDS should update their definition to make it clearer), but I think the default mapping for EEG.event.type should be "value", not "trial_type", as "value" is defined as "Marker value associated with the event".
- I can make it such that when EEGLAB field hasn't been selected for the BIDS field yet, the rest of the columns in the row won't be editable. I think that would be better?

The add/delete field button is a good idea and doable.

**Comment by arnodelorme** [comment]
> * For latency (sample) and latency (converted to s), does bids_export support these two options yet?

Yes, this is supported by default. In fact, if possible we would assign these by default and prevent any editing.

> * This has been discussed many times (and I think BIDS should update their definition to make it clearer), but I think the default mapping for EEG.event.type should be "value", not "trial_type", as "value" is defined as "Marker value associated with the event".

I agree. Cyril would disagree. Let's set it to "value".

> * I can make it such that when EEGLAB field hasn't been selected for the BIDS field yet, the rest of the columns in the row won't be editable. I think that would be better?

Yes, that would be great.

> The add/delete field button is a good idea and doable.

Great.
