### ISSUE TITLE
Participant interface

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#29]
I feel we should have one row per participant, not one row per dataset so it matches the BIDS participant file. It is not a big deal though and we should discuss it.

**Comment by arnodelorme** [comment]
Also we should have a button to edit the custom fields (add, remove or rename them)

**Comment by dungscout96** [comment]
One row per participant is definitely ideal, however that means participant/subject ID is guaranteed to exist for all datasets. Is there currently a way to enforce that?

**Comment by arnodelorme** [comment]
Good point. In a STUDY this is mandatory, so I do not think it is a problem. But return an error if any is missing.
