### ISSUE TITLE
eInfo ignored

### ISSUE THREAD

**Issue by alenarto** [sccn/bids-matlab-tools#3]
Hi folks. The bids_export.m file claims to add eInfo to the events.tsv. It does not do this. This variable is not processed in the bids_export.m file. Instead, there's a hardcoded routine to only write onset/duration/reactontime etc..

So the stated functionally needs to be implemented.
Agatha

**Comment by CPernet** [comment]
@arnodelorme should we finish this up properly?! 
thx @alenarto

**Comment by arnodelorme** [comment]
Agatha, did you try again recently. There has been a lot of changes. Make sure to use the GITHUB version so we can fix problems quickly if you encounter any. Closing this for now.

**Comment by alenarto** [comment]
Thanks Arno - I’ll take a look.
