### ISSUE TITLE
BIDS fields in first column

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#34]
First column -> put "BIDS field"
Onset -> "latency -> seconds"
Sample -> "latency"

Thanks @dungscout96

**Comment by dungscout96** [comment]
Onset -> "From sample", Blue font. Have callback make value unchangeable

**Comment by dungscout96** [comment]
@arnodelorme Should we just remove the Onset and Sample from the GUI table in total? We just need to make sure their bids info is recorded in eInfoDesc

**Comment by arnodelorme** [comment]
I think it would be nice to have it. You could disable the full row though.
Arno

**Comment by dungscout96** [comment]
Ok I kept them in. Unfortunately MATLAB table gui styling is only flexible after version 2019b. I disable editing EEGLAB field for onset and sample but didn't add any extra styling for them.

**Comment by arnodelorme** [comment]
Good to know.
