### ISSUE TITLE
Event selector

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#36]
Selecting "Choose EEGLAB field" ends up in the cell

**Comment by arnodelorme** [comment]
<img width="337" alt="Screen Shot 2020-10-22 at 4 41 17 PM" src="https://user-images.githubusercontent.com/1872705/96950397-eaf40a80-1485-11eb-941b-f7cd36b00385.png">

**Comment by dungscout96** [comment]
Fixed in 12e666b
