### ISSUE TITLE
BIDS events: duration automatically added even if it not in the event structure

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#37]

**Comment by dungscout96** [comment]
Should we not match BIDS "duration" with EEGLAB duration by default then? On the topic, latency and type are guaranteed to be in the event structure right?

**Comment by arnodelorme** [comment]
Yes I agree but sometimes duration is not availalble in the EEGLAB event. In this case we should leave blank

**Comment by dungscout96** [comment]
Fixed in ca69cbe42734eab0f29596fd8a1dcb89e9775914
