### ISSUE TITLE
Adding custom field

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#38]
It works but then pressing OK creates a crashes upon accepting. I added the field test and select edftype (from the test data available in the repo https://github.com/sccn/bids-matlab-tools-example)

**Comment by arnodelorme** [comment]
<img width="672" alt="Screen Shot 2020-10-22 at 4 46 34 PM" src="https://user-images.githubusercontent.com/1872705/96950555-445c3980-1486-11eb-907d-b439dee91771.png">

**Comment by dungscout96** [comment]
Fixed in d9825cf
