### ISSUE TITLE
Some internally generated error messages should be pop up

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#39]
Error messages (about not matching subjects in Excell file etc...) should be pop up using "warndlg2" instead of error in the command line.

**Comment by dungscout96** [comment]
Fixed in 5076884. I used errordlg2 for errors that terminate the program and warndlg2 for warning that allow the program to proceed after clicking OK

**Comment by arnodelorme** [comment]
Perfect
