### ISSUE TITLE
pop_participantinfo

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#42]
Crashes if no subject field in EEG. If this is the case, issue a pop-up error that subjects need to be defined before calling this function.

**Comment by dungscout96** [comment]
Here's the current check:
```
if ~isempty(EEG(1).subject)
     allSubjects = { EEG.subject };
elseif ~isempty(STUDY.datasetinfo(1).subject)
     allSubjects = { STUDY.datasetinfo.subject };
else
     errordlg2('No subject info found in either EEG or STUDY.datasetinfo. Please add using Study > Edit STUDY info');
     return
end
```
But it seems like returning after displaying the error dialog is causing crashes as some eeglab functions continue to run after that. What should be the proper way to terminate the program with EEGLAB?

**Comment by arnodelorme** [comment]
I would add 

If isfield(EEG, ’subject’) && ….

Just in case,

Arno

**Comment by dungscout96** [comment]
That's right. Added in 5571bda
