### ISSUE TITLE
Issue with coordinate system

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#44]
For the coordinate system issue, BIDS only allows "CapTrak" (RAS orientation and the origin between the ears). We currently have "EEGCoordinateSystem":"ARS". Can you help verify that the ARS is correct or we actually should have used CapTrak?

**Comment by dungscout96** [comment]
Only CapTrak is currently accepted as EEGCoordinateSystem. We'll try to get EEGLAB adopted.
