### ISSUE TITLE
'Stimuli' cell inputs are switched in bids_export documentation.

### ISSUE THREAD

**Issue by MarcRosenkranz** [sccn/bids-matlab-tools#46]
Hi,

I was trying to load in stimuli files via a script. According to the documentation a cell should follow 'stimuli' with the arrangement:
{ 'stim1', 'Users/xxx/stim1.mp3' }
For me it worked only when I switched the cell entries to:
{ 'Users/xxx/stim1.mp3', 'stim1' }

**Comment by cll008** [comment]
Thanks Marc for the report. Looks like this was fixed in 1576d21 partially, but I've cleaned it up a bit more in 872b126.
