### ISSUE TITLE
Import error (eegh)

### ISSUE THREAD

**Issue by cll008** [sccn/bids-matlab-tools#50]
https://github.com/sccn/bids-matlab-tools/blob/4734da70652d8ee8c78b61adf4aa6a476236ebaa/pop_importbids.m#L52

eegh error after importing a study. Probably because eegh is taking `stats` as the argument for eegh instead of `commands`:

```
Undefined operator '==' for input arguments of type 'struct'.

Error in eegh (line 104)
		if command == 0

```

**Comment by arnodelorme** [comment]
Thanks Clement. Fixed the issue and released version 5.2 because it was a blocker.
I think last time I released, I only tested the export function. Good argument for having test cases...
