### ISSUE TITLE
One session, one run, one task

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#57]
Change code so we can have the same session and run if the task is different

**Comment by cll008** [comment]
Quoting what Robert mentioned here to consolidate:

> So it would be just
> 
> sub-001_task-multiple_eeg.set
> 
> But if there is a nice chunking of the data possible over separate files, using that makes it much more clear. I understand that in your user's case the runs and tasks are equivalent, i.e. each file is a different run with (mostly) a different task. Technically you could do 
> 
> sub-001_task-multiple_run-01_eeg.set
> sub-001_task-multiple_run-02_eeg.set
> sub-001_task-multiple_run-03_eeg.set
> sub-001_task-multiple_run-04_eeg.set
> 
> and document elsewhere (in the eeg.json, and the README) what the mapping of runs on the “multiple” tasks is, but much clearer  is 
> 
> sub-001_task-resting_eeg.set
> sub-001_task-localizer_eeg.set
> sub-001_task-apa_run-01_eeg.set
> sub-001_task-apa_run-02_eeg.set

I think previously we planned to circumvent this issue by using 'task mixed' (#48), but not sure how we feel now. Do we plan to follow the 'clearer' convention? It seems better but also somewhat tricky to implement in the [bids_export heuristics](https://github.com/sccn/bids-matlab-tools/blob/ae05b80d932f70a2a8396763e84b7efd5f7e8e9a/bids_export.m#L507); may be easier if we tag everything with run number (i.e. sub-001_task-resting_run-01_eeg.set).

**Comment by arnodelorme** [comment]
Implemented, Clement to test.

**Comment by cll008** [comment]
So far seems like there is just a small typo and I had to use strcat instead of [] for the unique string generation. Need to test further.

We still need to change the way the [heuristics](https://github.com/sccn/bids-matlab-tools/blob/ae05b80d932f70a2a8396763e84b7efd5f7e8e9a/bids_export.m#L507) work. 

Also, the current file naming scheme still uses `opts.taskname` (which defaults to "Experiment") instead of using data.task. I think you mentioned you already implemented this, but was this on another branch?

**Comment by arnodelorme** [comment]
> So far seems like there is just a small typo and I had to use strcat instead of [] for the unique string generation. Need to test further.
> 
> We still need to change the way the heuristics work.
> 
> Also, the current file naming scheme still uses opts.taskname (which defaults to "Experiment") instead of using data.task. I think you mentioned you already implemented this, but was this on another branch?

Default is fine if task name is not specified for each file.
Requires testing (see function header I think.

Arno
