### ISSUE TITLE
BIDS export channel type

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#60]
Add channel types from channel location structure (even if template).

**Comment by arnodelorme** [comment]
@cll008  to check

**Comment by cll008** [comment]
bids_export already takes care of this [here](https://github.com/sccn/bids-matlab-tools/blob/ae05b80d932f70a2a8396763e84b7efd5f7e8e9a/bids_export.m#L911)

**Comment by arnodelorme** [comment]
Needs to fill from template file. Add to template file.

**Comment by cll008** [comment]
Continued as #64
