### ISSUE TITLE
BIDS task and task condition import/export

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#63]
In pop_taskinfo.m, when the checkbox to import task condition is set, replace tasks with the EEG.condition field. Make sure this is imported property when we import the data as well.

**Comment by dungscout96** [comment]
This might confound the meaning and usage of TaskName. If people name their EEG.condition without task name (thinking in terms of different conditions of the same task), then there would be no task name. BIDS uses TaskName to form filename with `task-TaskName` and future tools might extract task information automatically, so this might cause misunderstanding.

**Comment by arnodelorme** [comment]
Yes, I agree. Not an easy problem to solve. Maybe we should add an extract field EEG.task.

**Comment by dungscout96** [comment]
That would probably a good field to have for EEGLAB in general.

**Comment by cll008** [comment]
fixed by #68
