### ISSUE TITLE
bids_spreadsheet2participants.m: Data.Age type

### ISSUE THREAD

**Issue by cll008** [sccn/bids-matlab-tools#67]
https://github.com/sccn/bids-matlab-tools/blob/182d1e3076cb7465f4495e6eafccf3fba7d5a00a/bids_spreadsheet2participants.m#L127-L130

Thanks @CPernet for this function, saved me a lot of work. I had some trouble with some Data.Age that was already cast as double (commenting out these lines worked). Not sure if it's the formatting of my .xlsx or some changes in `readtable` (MATLAB 2019a).

**Comment by CPernet** [comment]
can you try an update rather than a comment -- what about
``` matlab
 for v = 1:length(Data.age) 
     if ischar(Data.age{v})
        Data.age{v} = str2double(Data.age{v}); 
     else
        Data.age{v} = Data.age{v}; 
     end
 end 
```

if this work, submit a PR 
thx
