### ISSUE TITLE
pop_eventInfo `onset` field

### ISSUE THREAD

**Issue by cll008** [sccn/bids-matlab-tools#69]
Onset BIDS field cannot be matched to EEGLAB field (which defaults to 'from sample') in GUI. This pair is then not written to eInfo, and exported events.tsv contain nan onset values (and thus causes errors during checkset)

**Comment by dungscout96** [comment]
This is related to the bug reported by Agatha which is now fixed. Onset and sample are automatically filled even with non-empty eInfo at bids_export. Can you verify and close if it's good?
