### ISSUE TITLE
pop_participantinfo.m sort natural "participant_id"

### ISSUE THREAD

**Issue by CorentinWicht** [sccn/bids-matlab-tools#70]
Dear EEGLAB-BIDS developers,

I am reporting here an issue related to the `pop_participantinfo.m` function. 

When running  `EEG = pop_participantinfo(EEG, STUDY);`, I realize that the participant_id column does not follow natural ordering:
![image](https://user-images.githubusercontent.com/52161904/112629975-47909280-8e35-11eb-9c1e-7e47db7a0cd4.png)

While I made sure to do so in the STUDY structure:
![image](https://user-images.githubusercontent.com/52161904/112630065-668f2480-8e35-11eb-8a27-a310231398dd.png)

Why such a mismatch? Could it be fixed? 
(by the way this function works really great: https://ch.mathworks.com/matlabcentral/fileexchange/10959-sort_nat-natural-order-sort)

It makes coding really messy since there is a mismatch regarding files ordering...

Best wishes,

Corentin Wicht

**Comment by dungscout96** [comment]
This is indeed due to the sorting on string starting with numbers not using natural sorting order. Fixed in 82bb4ad. Thanks for the function suggestion!
