### ISSUE TITLE
Error iTask as an index in bids_export.m

### ISSUE THREAD

**Issue by CorentinWicht** [sccn/bids-matlab-tools#71]
Dear EEGLAB developers,

I may have identified an issue in the `bids_export.m` function related to the `iTask` variable.

In the function description you suggest that the `.task` structure field be a **cell array of character vectors**:
`subject(1).task    = { 'go-no task' 'control task' 'go-no task' 'control task' }`

Then, in line 636 you wrote:
` iTask = files(iSubj).task(iSet);`

The problem is that `iTask` is supposed to be **an index** to retrieve the name of the corresponding task in `files(iSubj).task` (line 637):
`fileOut = fullfile(opt.targetdir, subjectStr, sprintf('ses-%2.2d', iSess), 'eeg', [ subjectStr sprintf('_ses-%2.2d', iSess) '_task-' char(files(iSubj).task(iTask)) '_eeg' files(iSubj).file{iSet}(end-3:end)]);`

Hence, running lines 636-637 returns the error: 
![image](https://user-images.githubusercontent.com/52161904/114000561-6a6e6e00-985b-11eb-9bb5-167122427768.png)

Why not rewrite line 637 accordingly ? :
`fileOut = fullfile(opt.targetdir, subjectStr, sprintf('ses-%2.2d', iSess), 'eeg', [ subjectStr sprintf('_ses-%2.2d', iSess) '_task-' char(iTask) '_eeg' files(iSubj).file{iSet}(end-3:end)]);`

Best,

Corentin W.

**Comment by cll008** [comment]
Thanks for catching that Corentin.
Are you currently processing a dataset with multiple sessions and tasks but a single run?
Would removing L636 ` iTask = files(iSubj).task(iSet);` and replacing L637 `char(files(iSubj).task(iTask))` with `char(files(iSubj).task(iSet))` work? I was having some issues here but clearly I didn't fixed it correctly...

**Comment by CorentinWicht** [comment]
Dear Clement, 

many thanks for your prompt reply. 
I am indeed working on a dataset containing 2 tasks (each in a single run) X 3 (within-subject) sessions and your fix works as well. 

Best,

Corentin W.
