### ISSUE TITLE
pop_validatebids: Formatting issue

### ISSUE THREAD

**Issue by dungscout96** [sccn/bids-matlab-tools#72]
Issue raised by Corentin Wicht in https://github.com/bids-standard/bids-validator/issues/1262. Caused by MATLAB not supporting color output.

**Comment by nellh** [comment]
If there's a limitation with configuring the terminal settings in MATLAB, we could add an option to disable colors to bids-validator. There's also the --json flag to get JSON output that contains the same information as the text output mode without colors or formatting.

**Comment by dungscout96** [comment]
Thanks @nellh. MATLAB doesn't have native support for color output on the command window. It would be great if bids-validator provides option to disable color. Otherwise we'll have to parse the JSON output using the flag you mentioned and format accordingly.

**Comment by nellh** [comment]
Can you control the terminal settings? We do disable color if the terminal doesn't advertise support for it but in this case it seems it's advertising it without actually supporting it.

**Comment by arnodelorme** [comment]
The only color Matlab supports is red (use fprintf(2, …..))

**Comment by dungscout96** [comment]
MATLAB text editors (command window where validator result is displayed being one) seemingly use Java JTextArea under the hood and support some text coloring for their syntax highlighting so maybe that's why there's the false advertising. But it's not a terminal similar to a normal shell on; any color change must be done by hacking the underlying JTextArea and setting color for each text segment. So it would be great if we can explicitly disable color for bids-validator output.
