### ISSUE TITLE
bids export reduces EEG.event.sample by 1

### ISSUE THREAD

**Issue by cll008** [sccn/bids-matlab-tools#75]
EEG.event.sample is reduced by 1 on each subsequent export (when using p300 test case)

**Comment by cll008** [comment]
https://github.com/sccn/bids-matlab-tools/blob/2473258b90b401b1572d9580591c9f26f2099e67/bids_export.m#L815
Hi @arnodelorme any idea what the  `-1` here does? (added in ec5f579)

**Comment by dungscout96** [comment]
Just came across the same issue. Was wondering why that's the case

**Comment by cll008** [comment]
According to Arno: This is in export because BIDS sample starts counting at 0 
Solution: I will add 1 back in import.
