### ISSUE TITLE
Discrepancy in run between ALLEEG and STUDY

### ISSUE THREAD

**Issue by crisglav** [sccn/bids-matlab-tools#77]
When I load a BIDS dataset with only one run per task with the function pop_importbids(), I get ALLEEG with the run field empty for every subject, but in STUDY  the run field is set to 1. This raises an inconsistency when calling pop_participantsinfo(): 'Information between STUDY and single datasets is inconsistent'.

I believe the problem would be solved by replacing line 258 of pop_importbids()
`iRun = 1;` by `iRun = []`

Best,
Cristina

**Comment by cll008** [comment]
Thanks for reporting the issue Cristina, I'm hoping you can provide some more info. Technically, if your data is one run per task then `EEG.run` and `ALLEEG.run` should be one (changing line258 fixes the current issue but would cause problems downstream). When you are running `pop_importbids.m`, is iRun assigned to `EEG.run` correctly in the following line? 
https://github.com/sccn/bids-matlab-tools/blob/df2518b7e3010c96246c6af1c838c076f2be162d/pop_importbids.m#L425

**Comment by crisglav** [comment]
Hi! Problem was solved. It was not a bug after all! Thanks for looking at it
