### ISSUE TITLE
Issue with HED validation for BIDS export

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#87]
@dungscout96 would you mind looking into this

1. Load the STUDY at 

NEMAR disk 

bugs/hed_bids/ds002680-download

(there is a study with 2 subjects only which is faster to load)

2. Export using the BIDS exporter (pull latest changes) all default

3. Try exporting

openneuro upload -i --dataset ds002680 export_folder

The validator choke on HED validation

**Comment by dungscout96** [comment]
Reason being HED column is being exported automatically for events.tsv even when there's no tag from the datasets. I updated the behavior of bidsexport to not write the HED column by default, which is not what we want for HED-3G anyway (we want to write events.json files instead which has been implemented in a previous commit). I fixed the STUDY and tested the export with BIDS online validator. No HED issue but there's error for the stim_file.
The fixed STUDY is being uploaded back to the server under `derivatives_fixed_HED`
