### ISSUE TITLE
Issue Specifying Participant Info Levels

### ISSUE THREAD

**Issue by ams023** [sccn/bids-matlab-tools#9]
When entering participant info, all levels can only be specified ("click to specify") before pressing "ok." It would be useful to be able to go back and add in this information and/or edit it after pressing "ok"
![Submission](https://user-images.githubusercontent.com/65685539/82518522-6c5d0080-9ad4-11ea-8d6f-6f5574e236f0.JPG)

**Comment by dungscout96** [comment]
Solved in [a911c82](https://github.com/sccn/bids-matlab-tools/commit/9bbd9fc68872d66676bae47a4108ea062e9a5130)
