### ISSUE TITLE
pop_validatebids() .EEGChannelCount should be integer

### ISSUE THREAD

**Issue by CorentinWicht** [sccn/bids-matlab-tools#92]
Dear Developper,

I've just exported BIDS files for the first time using your plugin and while applying the `pop_validatebids` function to actually validate the output, I got the following message:

```
>> pop_validatebids(ExportPath)
bids-validator@undefined

	[31m1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)[39m
		./sub-001/ses-01/eeg/sub-001_ses-01_task-GNG_eeg.json
			Evidence: .EEGChannelCount should be integer
		./sub-001/ses-01/eeg/sub-001_ses-01_task-RVIP_eeg.json
			Evidence: .EEGChannelCount should be integer
[31m... and 278 more files having this issue (Use --verbose to see them all).[39m
[36m	Please visit https://neurostars.org/search?q=JSON_SCHEMA_VALIDATION_ERROR for existing conversations about this issue.[39m

	[33m1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)[39m

[36m	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.[39m

	[33m2: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered based on the presence of only one author field. Please ignore if all contributors are already properly listed. (code: 102 - TOO_FEW_AUTHORS)[39m

[36m	Please visit https://neurostars.org/search?q=TOO_FEW_AUTHORS for existing conversations about this issue.[39m
```

That's how my "./sub-001/ses-01/eeg/sub-001_ses-01_task-GNG_eeg.json" looks like:
![image](https://user-images.githubusercontent.com/52161904/137708371-8e5b5898-828a-4313-8f32-debc02a049f0.png)

Would you have any idea why I got these error messages when trying to validate the output?

Many thanks and best regards,

Corentin Wicht

**Comment by Remi-Gau** [comment]
I will let the plugin developpers confirm but it seems that you can set that info manually at export to override info read from file:

https://github.com/sccn/bids-matlab-tools/blob/dabf9e945909f4f2735cc2ea8e47513f4e1c64de/bids_export.m#L220

maybe you can use that approach.
