### ISSUE TITLE
HED field in events

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#98]
Do not export the HED field when present in the EEGLAB event structure by default.

**Comment by dungscout96** [comment]
I think rather than trying to detect whether the HED column was automatically generated by EEGLAB with n/a values, in order to decide if events.json should contain info about it, I will update the bids and HED plugins to not create this column by default

**Comment by dungscout96** [comment]
I checked and this is already the case. HED column is already no longer automatically written out by default.
